// Mocks generated by Mockito 5.4.5 from annotations
// in releaser/test/router/add_instruction_command_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:archive/src/archive/archive_file.dart' as _i9;
import 'package:archive/src/io/zip_file_encoder.dart' as _i5;
import 'package:archive/src/io/zip_file_progress.dart' as _i7;
import 'package:archive/src/util/output_file_stream.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:releaser/software/software.dart' as _i2;
import 'package:releaser/software/software_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSoftware_0 extends _i1.SmartFake implements _i2.Software {
  _FakeSoftware_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SoftwareRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoftwareRepository<T> extends _i1.Mock
    implements _i3.SoftwareRepository<T> {
  @override
  _i4.Future<_i2.Software> save(_i2.Software? software) =>
      (super.noSuchMethod(
            Invocation.method(#save, [software]),
            returnValue: _i4.Future<_i2.Software>.value(
              _FakeSoftware_0(this, Invocation.method(#save, [software])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Software>.value(
              _FakeSoftware_0(this, Invocation.method(#save, [software])),
            ),
          )
          as _i4.Future<_i2.Software>);

  @override
  _i4.Future<List<_i2.Software>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i4.Future<List<_i2.Software>>.value(<_i2.Software>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Software>>.value(
              <_i2.Software>[],
            ),
          )
          as _i4.Future<List<_i2.Software>>);

  @override
  _i4.Future<_i2.Software?> findByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#findByName, [name]),
            returnValue: _i4.Future<_i2.Software?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Software?>.value(),
          )
          as _i4.Future<_i2.Software?>);

  @override
  _i4.Future<bool> delete(_i2.Software? software) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [software]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [ZipFileEncoder].
///
/// See the documentation for Mockito's code generation for more information.
class MockZipFileEncoder extends _i1.Mock implements _i5.ZipFileEncoder {
  @override
  _i4.Future<void> zipDirectory(
    _i6.Directory? dir, {
    String? filename,
    int? level,
    bool? followLinks = true,
    void Function(double)? onProgress,
    DateTime? modified,
    _i7.ZipFileProgress? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #zipDirectory,
              [dir],
              {
                #filename: filename,
                #level: level,
                #followLinks: followLinks,
                #onProgress: onProgress,
                #modified: modified,
                #filter: filter,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void open(String? zipPath) => super.noSuchMethod(
    Invocation.method(#open, [zipPath]),
    returnValueForMissingStub: null,
  );

  @override
  void create(String? zipPath, {int? level, DateTime? modified}) =>
      super.noSuchMethod(
        Invocation.method(
          #create,
          [zipPath],
          {#level: level, #modified: modified},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createWithStream(
    _i8.OutputFileStream? outputFileStream, {
    int? level,
    DateTime? modified,
  }) => super.noSuchMethod(
    Invocation.method(
      #createWithStream,
      [outputFileStream],
      {#level: level, #modified: modified},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> addDirectory(
    _i6.Directory? dir, {
    bool? includeDirName = true,
    int? level,
    bool? followLinks = true,
    void Function(double)? onProgress,
    _i7.ZipFileProgress? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addDirectory,
              [dir],
              {
                #includeDirName: includeDirName,
                #level: level,
                #followLinks: followLinks,
                #onProgress: onProgress,
                #filter: filter,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addFileSync(_i6.File? file, [String? filename, int? level]) =>
      super.noSuchMethod(
        Invocation.method(#addFileSync, [file, filename, level]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> addFile(_i6.File? file, [String? filename, int? level]) =>
      (super.noSuchMethod(
            Invocation.method(#addFile, [file, filename, level]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addArchiveFile(_i9.ArchiveFile? file) => super.noSuchMethod(
    Invocation.method(#addArchiveFile, [file]),
    returnValueForMissingStub: null,
  );

  @override
  void closeSync() => super.noSuchMethod(
    Invocation.method(#closeSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
