name: releaser
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  csv: ^5.1.1
  equatable: ^2.0.5
  mockito: ^5.4.4
  path: ^1.9.0
  uuid: ^4.3.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.0.0
  test: ^1.25.2
